### ISSUE TITLE
Empty web page in OF

### ISSUE THREAD

**Issue by naxombl4** [igniterealtime/openfire-gojara-plugin#2]
Hello!
In the settings of the server OF "Spectrum2 Stats" and "Gojara Settings" lead to blank pages. It is not possible to configure external transports on new installations. Version of the server Openfire 4.3.2; plugin version (2.2.3-SNAPSHOT 4.0.0 Dec 28, 2018 2:47:51 PM)
Stable version of the plugin does not start on version 4.3.2

**Comment by wrooot** [comment]
This is essentially what https://github.com/igniterealtime/openfire-gojara-plugin/issues/1 is about.

**Comment by wrooot** [comment]
Submitted https://github.com/igniterealtime/openfire-gojara-plugin/pull/3
