### ISSUE TITLE
Every Gojara Page not Found HTTP ERROR 404

### ISSUE THREAD

**Issue by QomariSanjaya** [igniterealtime/openfire-gojara-plugin#4]
Using Openfire 4.5.1
Gojara 2.2.3-SNAPSHOT
Debian 10

**Comment by Knezzen** [comment]
I have the same issue with 4.6.2 and 4.6.3 as well. Would be great to find a solution for this!

**Comment by guusdk** [comment]
This should be fixed in the SNAPSHOT build that was created on March 23, 2022: https://www.igniterealtime.org/projects/openfire/plugin-archive.jsp?plugin=gojara
